# Generated by Django 5.2.8 on 2025-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_itemimage_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
