# Generated by Django 5.2.8 on 2025-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemimage_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
