# Generated by Django 5.2.8 on 2025-11-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_ai_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='ai_analysis',
        ),
    ]
