# Generated by Django 5.2.8 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_itemimage_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='co2_saved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eco_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='water_saved',
            field=models.FloatField(default=0.0),
        ),
    ]
