# Generated by Django 5.1 on 2026-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_social_links_follow_order_review_wishlist'),  # Update this to match your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eco_tier',
            field=models.CharField(
                choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')],
                default='BRONZE',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='items_sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='items_bought_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EcoPointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    choices=[
                        ('ITEM_LISTED', 'Item Listed'),
                        ('ITEM_PURCHASED', 'Item Purchased'),
                        ('PROFILE_COMPLETED', 'Profile Completed'),
                        ('SUSTAINABLE_BRAND', 'Sustainable Brand Bonus'),
                        ('LONGEVITY_BONUS', 'Item Longevity Bonus'),
                    ],
                    max_length=50
                )),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='eco_history', to='core.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ecopointshistory',
            index=models.Index(fields=['user', '-created_at'], name='core_ecopoi_user_id_created_idx'),
        ),
    ]
