# Generated by Django 5.2.8 on 2026-07-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_is_sold'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ecopointshistory',
            new_name='core_ecopoi_user_id_fe356e_idx',
            old_name='core_ecopoi_user_id_created_idx',
        ),
    ]
