# Generated by Django 5.2.8 on 2026-08-27 14:39
# Hand-edited: the autodetector produced RemoveField + AddField for the
# stripe_payment_intent -> stripe_checkout_session_id rename, which would
# DROP the column and its data (the real cs_... session ids on every
# existing production order) rather than preserve it. Replaced with
# RenameField (a metadata-only rename, no data loss) followed by AlterField
# to add the index. Verified via `sqlmigrate` before this ran against prod.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_ecopoi_user_id_created_idx_core_ecopoi_user_id_fe356e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='stripe_checkout_session_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
