# Generated by Django 5.2.8 on 2026-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_processedstripeevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-eco_points'], name='core_customuser_eco_points_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='core_item_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', '-created_at'], name='core_item_sold_created_idx'),
        ),
    ]
